apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: nginx
        image: philippaul/node-demo-app:01
        ports:
        - containerPort: 80
